### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by mmirus** [ipo-dyale/dereksitebuild#3]
CSS seems good--didn't spot any big issues here. A handful of minor things below.

---

1. Inconsistent indentation
2. Unnecessary or duplicate declarations (e.g., two 'font-size' declarations on 'body')

Didn't spot too many of these, though, in my once-over.

---

Inconsistent ordering of properties - not necessarily a problem, but in case it's useful for you, I find it's helpful to generally try to put my properties in the same order across style blocks. Not something you have to do if it's not useful. I don't have a formal system, but here's an example:

```css
.aplb-links a {
  position: relative;
  display: inline-block;
  min-width: 51%;
  padding: 0.4rem 0;
  margin: 0.75rem 0;
  color: #000;
  text-align: center;
  vertical-align: middle;
  border-bottom: 1px dotted rgba(0, 0, 0, 0.5);
}
```

Position -> box model -> width / height -> padding -> margin -> text styles -> borders.

Again, not something I have 100% systematized and consistent. Not sure if other developers do something similar.

---

Why `:last-child` here?

```css
#header-menu li:last-child{
	font-weight: bold;
}
```

---

This probably has no effect / isn't needed:

```css
.navleft {
	margin-right: auto;
}
```

---

Media queries - As a general project I recommend developing mobile first and structuring your CSS to reflect that; your CSS does the reverse, handling general styles / larger devices first and then specifically targeting smaller form factors.

Mobile first isn't required for CSS to be good, and in some cases there may be good reasons to do the reverse, but I would recommend having mobile first as your default in how you design and how you write your code.

---

In your media queries, did you try just adjusting the body font size? Curious if that would have taken care of all of the below elements in your two MQs:

```css
h1, h2, h3, h4, h5, h6 {
	font-size: 1.23em;
}

p, .date {
	font-size: 16px;
}
```

---

These are all very small items. I'm sure there's room for optimization, but I didn't spot any significant problems in my quick review.
